version: '3'
services:
  iritani_last-task:
    restart: always
    build: .
    container_name: 'iri-container_computer-programing'
    working_dir: '/root'
    tty: true
    volumes:
      - ./applications:/root/applications
    ports:
      - "5000:5000"
    environment:
      TZ: Asia/Tokyo
