MAIN_URL: 'https://suumo.jp/jj/chintai/ichiran/FR301FC005/?ar=030&bs=040&ra=012&rn=0025&ek=002504690&cb=0.0&ct=9999999&mb=0&mt=9999999&md=06&et=9999999&cn=9999999&shkr1=03&shkr2=03&shkr3=03&shkr4=03&sngz=&po1=25&po2=99&pc=100&page='

FILE:
  BACKUP_FILE_NAME: 'house_price.csv'
  PNG_FILE_NAME: 'ScatterRegression.png'

DIRECTORY:
  ML_LEARNING_BASE_DIR: '/applications/machine_learning/'

DATA_PROCESS:
  ITERS: 50000
  ALPHA: 0.01

MY_HOME_TERM:
  FAR_FROM_STATION: 13.0
  AGE: 29.0
  PRICE: 8.3